"""Fix foreign keys issue

Revision ID: 052028fd9df8
Revises: 7cf7b47c8e25
Create Date: 2020-04-16 09:52:14.916274

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '052028fd9df8'
down_revision = '7cf7b47c8e25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dvds_ibfk_2', 'dvds', type_='foreignkey')
    op.drop_constraint('magazines_ibfk_2', 'magazines', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('magazines_ibfk_2', 'magazines', 'user', ['borrower_id'], ['id'])
    op.create_foreign_key('dvds_ibfk_2', 'dvds', 'user', ['borrower_id'], ['id'])
    # ### end Alembic commands ###