"""Add borrower Name

Revision ID: 1e4ce83b1d66
Revises: 052028fd9df8
Create Date: 2020-04-16 11:26:40.975160

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1e4ce83b1d66'
down_revision = '052028fd9df8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dvds', sa.Column('borrower_name', sa.String(length=50), nullable=True))
    op.add_column('magazines', sa.Column('borrower_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('magazines', 'borrower_name')
    op.drop_column('dvds', 'borrower_name')
    # ### end Alembic commands ###