"""Add magazine table and format and rating to DVDs

Revision ID: 7cf7b47c8e25
Revises: 
Create Date: 2020-04-16 09:47:07.855339

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7cf7b47c8e25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dvds', sa.Column('format', sa.String(length=20), nullable=False))
    op.add_column('dvds', sa.Column('rating', sa.String(length=5), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dvds', 'rating')
    op.drop_column('dvds', 'format')
    # ### end Alembic commands ###