"""Add formats

Revision ID: 9bfedf84bc2b
Revises: b821340d2a25
Create Date: 2020-04-16 13:53:59.014247

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9bfedf84bc2b'
down_revision = 'b821340d2a25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dvds', sa.Column('format_4k', sa.Boolean(), nullable=True))
    op.add_column('dvds', sa.Column('format_bluray', sa.Boolean(), nullable=True))
    op.add_column('dvds', sa.Column('format_dvd', sa.Boolean(), nullable=True))
    op.drop_column('dvds', 'format')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dvds', sa.Column('format', mysql.VARCHAR(length=20), nullable=False))
    op.drop_column('dvds', 'format_dvd')
    op.drop_column('dvds', 'format_bluray')
    op.drop_column('dvds', 'format_4k')
    # ### end Alembic commands ###