"""Add rules check

Revision ID: b821340d2a25
Revises: be65e8a36cc5
Create Date: 2020-04-16 12:50:21.539864

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b821340d2a25'
down_revision = 'be65e8a36cc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('rules_read', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'rules_read')
    # ### end Alembic commands ###