"""Add Owner Name to DVDs and Magazines

Revision ID: be65e8a36cc5
Revises: 1e4ce83b1d66
Create Date: 2020-04-16 12:27:30.849531

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'be65e8a36cc5'
down_revision = '1e4ce83b1d66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dvds', sa.Column('owner_name', sa.String(length=50), nullable=True))
    op.add_column('magazines', sa.Column('owner_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('magazines', 'owner_name')
    op.drop_column('dvds', 'owner_name')
    # ### end Alembic commands ###